version: '3'

services:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    image: mariadb
    restart: always
    networks:
      - inception
    expose:
      - "3306"
    volumes:
      - db_vol:/var/lib/mysql
    env_file:
      - .env
  nginx:
    depends_on:
      - wordpress
    container_name: nginx
    build: ./requirements/nginx
    image: nginx
    restart: always
    ports:
      - "443:443"
    volumes:
      - wordpress_vol:/var/www/html/wordpress
    networks:
      - inception
    env_file:
      - .env
  wordpress:
    depends_on:
      - mariadb
    container_name: wordpress
    build: ./requirements/wordpress
    image: wordpress
    restart: always
    volumes:
      - wordpress_vol:/var/www/html/wordpress
    expose: 
      - "9000"
    networks:
      - inception
    env_file:
      - .env

networks:
  inception:
    driver: bridge

volumes:
  wordpress_vol: {}
  db_vol: {}